/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.6.20" 
    id("org.jetbrains.kotlin.plugin.serialization") version "1.4.20"

    application
}

repositories {
	google()
    mavenCentral() 
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom")) 
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8") 
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.6.20")

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.2")

    implementation(platform("org.http4k:http4k-bom:4.20.0.0"))
    implementation("org.http4k:http4k-core")
    implementation("org.http4k:http4k-server-apache")
    implementation("org.http4k:http4k-client-apache")
    implementation("org.http4k:http4k-format-jackson")
    implementation("org.http4k:http4k-server-jetty")

    implementation("com.charleskorn.kaml:kaml:0.42.0")

    // testImplementation("org.jetbrains.kotlin:kotlin-test") 
    // testImplementation("org.jetbrains.kotlin:kotlin-test-junit") 
}

application {
    mainClass.set("com.cachigo.MainKt") 
}